[package]
name = "time"
version = "0.2.3"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration"]
categories = ["date-and-time"]
readme = "README.md"
license = "MIT OR Apache-2.0"
# TODO Add GitHub Actions badge once rust-lang/crates.io#1838 is merged.
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."

[package.metadata.docs.rs]
features = ["deprecated", "panicking-api", "serde"]

[features]
default = ["deprecated"]
deprecated = []
alloc = ["serde/alloc"]
panicking-api = []

[dependencies]
serde = { version = "1", optional = true, default-features = false, features = ["derive"] }
time-macros = { version = "0.1", path = "time-macros" }
rustversion = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["minwinbase", "minwindef", "timezoneapi", "winnt"] }

[workspace]
members = [
    "time-macros",
    "time-macros-impl",
]
